/**
 * Shared utility functions and constants
 */

import profile from '@/data/profile.json';

// Site configuration
export const SITE_URL = 'https://henrymatar.github.io';
export const AUTHOR_NAME = profile.name;
export const TWITTER_HANDLE = ''; // PLACEHOLDER - add your handle (e.g. '@henrymatar') or leave blank if you don't use X/Twitter
/**
 * The portrait. Used for JSON-LD `image`, where the value should be a picture
 * of the person, not a designed card.
 */
export const SITE_IMAGE_PATH = 'Headshot_temp.png';
export const SITE_IMAGE_DIMENSIONS = {
  width: 1024,
  height: 1024,
} as const;

/**
 * The share card, generated by `npm run og` and committed to `public/`.
 *
 * Every page points at this one path explicitly. Next's `opengraph-image`
 * file convention is not used: a route-level `openGraph` object replaces the
 * inherited one wholesale, which left every subpage with no image at all, and
 * the metadata route emits an extensionless file that GitHub Pages serves as
 * application/octet-stream.
 */
export const SHARE_IMAGE_PATH = '/og.png';
export const SHARE_IMAGE_DIMENSIONS = {
  width: 1200,
  height: 630,
} as const;

// Canonical one-line bio, shared across page metadata, OpenGraph, and JSON-LD.
export const SITE_DESCRIPTION =
  'Electrical Engineering student at CU Boulder, currently a Systems Engineering Intern at Lockheed Martin. Focused on hardware design, embedded systems, and PCB design.';

// Image dimension constants
export const PROJECT_IMAGE = {
  width: 600,
  height: 400,
} as const;

// Skill competency
export const MAX_COMPETENCY = 5;

/**
 * Formats a date string to a human-readable format.
 * Parses as UTC to avoid timezone shifts.
 */
export function formatDate(dateStr: string): string {
  if (!dateStr) return '';
  // Parse as UTC to avoid timezone shifts
  const date = new Date(`${dateStr}T12:00:00`);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}