import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { SchemaGraph } from '@/components/Schema';
import PageWrapper from '@/components/Template/PageWrapper';
import PostContent from '@/components/Writing/PostContent';
import ReadingProgress from '@/components/Writing/ReadingProgress';
import {
  type ImageSize,
  readImageSize,
  readPostImageSizes,
} from '@/lib/imageSize';
import { sharedOpenGraph, sharedTwitter } from '@/lib/metadata';
import { getPostBySlug, getPostSlugs, type Post } from '@/lib/posts';
import {
  blogPostingNode,
  breadcrumbNode,
  HOME_URL,
  webPageNode,
} from '@/lib/schema';
import { AUTHOR_NAME, formatDate, SITE_URL } from '@/lib/utils';

interface PageProps {
  params: Promise<{ slug: string }>;
}

interface PostImage extends ImageSize {
  alt: string;
  url: string;
}

function measureImage(publicPath: string, alt: string): PostImage {
  // Read off the file rather than assumed: a missing or mis-sized image stops
  // the build instead of shipping share metadata that scrapers reject.
  return {
    ...readImageSize(publicPath),
    alt,
    url: new URL(publicPath, SITE_URL).toString(),
  };
}

/**
 * The share card for a post.
 *
 * Every published post has one generated by `npm run og` and committed to
 * `public/og/writing/<slug>.png` — `scripts/og-inputs.mjs` owns that path, and
 * `npm run og:check` fails CI when a card goes stale. Posts used to fall back to
 * the site card, which made a shared essay byte-identical to a shared homepage.
 *
 * A post's own `image` is deliberately not used here: `summary_large_image`
 * wants 1.91:1, and an article screenshot is whatever shape it is. It is the
 * article image below instead, which is what JSON-LD asks for.
 */
function getShareImage(post: Post): PostImage {
  return measureImage(
    `/og/writing/${post.slug}.png`,
    `${post.title} — ${AUTHOR_NAME}`,
  );
}

/**
 * The image that represents the article itself, for structured data: the
 * screenshot or diagram the post names, and otherwise its share card.
 */
function getArticleImage(post: Post): PostImage {
  return post.image && post.imageAlt
    ? measureImage(post.image, post.imageAlt)
    : getShareImage(post);
}

export function generateStaticParams() {
  const slugs = getPostSlugs();
  return slugs.map((slug) => ({ slug }));
}

export async function generateMetadata({
  params,
}: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const post = getPostBySlug(slug);

  if (!post) {
    return {
      title: 'Post Not Found',
    };
  }

  const url = `${SITE_URL}/writing/${post.slug}/`;
  const image = getShareImage(post);

  // Built once and spread into both cards, so the two can never disagree about
  // the share image.
  const shareImage = {
    images: [
      {
        url: image.url,
        width: image.width,
        height: image.height,
        alt: image.alt,
      },
    ],
  };

  // Spreading the shared blocks matters: a route-level `openGraph` replaces
  // the inherited one, so anything omitted here — images, siteName, locale,
  // twitter:site — simply disappears from post pages.
  return {
    title: post.title,
    description: post.description,
    alternates: { canonical: url },
    openGraph: {
      ...sharedOpenGraph,
      type: 'article',
      title: post.title,
      description: post.description,
      url,
      publishedTime: post.date,
      authors: [AUTHOR_NAME],
      ...shareImage,
    },
    twitter: {
      ...sharedTwitter,
      title: post.title,
      description: post.description,
      ...shareImage,
    },
  };
}

export default async function PostPage({ params }: PageProps) {
  const { slug } = await params;
  const post = getPostBySlug(slug);

  if (!post) {
    notFound();
  }

  const postUrl = `${SITE_URL}/writing/${post.slug}/`;
  const writingUrl = `${SITE_URL}/writing/`;
  const imageSizes = readPostImageSizes(post.content);
  const articleImage = getArticleImage(post);

  return (
    <PageWrapper>
      <SchemaGraph
        nodes={[
          webPageNode({
            url: postUrl,
            name: post.title,
            description: post.description,
            hasBreadcrumb: true,
          }),
          blogPostingNode(post, articleImage),
          breadcrumbNode(postUrl, [
            { name: 'Home', url: HOME_URL },
            { name: 'Writing', url: writingUrl },
            { name: post.title, url: postUrl },
          ]),
        ]}
      />
      <article className="post-page">
        <ReadingProgress />
        <header className="post-header">
          <time className="post-date" dateTime={post.date}>
            {formatDate(post.date)}
          </time>
          <h1 className="post-title">{post.title}</h1>
          <p className="post-description">{post.description}</p>
        </header>
        <div className="post-content prose">
          <PostContent content={post.content} imageSizes={imageSizes} />
        </div>
      </article>
    </PageWrapper>
  );
}
