#!/usr/bin/env node
/**
 * Fails CI when a committed share card no longer matches the repository.
 *
 * The cards are generated by `npm run og` and committed, so nothing at build
 * time notices when the design, the profile facts, the colour tokens, or a post
 * changes underneath them. This recomputes every input the generator used and
 * compares it against `public/og.meta.json`.
 *
 * This script checks ledger consistency first; the `og:check` package command
 * follows it with a fresh render in `generate-og.mjs --check`, which proves the
 * committed pixels actually came from these inputs.
 *
 * It is also the gate on the one asset in `public/` that is derived from
 * `content/writing/`: a card left behind by a post that became a draft, or was
 * renamed, would stay publicly fetchable with its title rendered into it.
 */
import { readdir, readFile } from 'node:fs/promises';

import {
  HOME_CARD_PATH,
  imageDigest,
  LEDGER_PATH,
  POST_CARD_DIRECTORY,
  publicFile,
  readCardInputs,
} from './og-inputs.mjs';

const root = process.cwd();
// Deliberately an independent literal rather than the generator's constant, so
// a typo there cannot make both sides agree on the wrong card size.
const EXPECTED_SIZE = { width: 1200, height: 630 };
const REGENERATE = 'Run `npm run og` and commit the generated files.';

const failures = [];
const fail = (message) => failures.push(message);
const same = (a, b) => JSON.stringify(a) === JSON.stringify(b);

const [ledger, inputs] = await Promise.all([
  readFile(publicFile(root, LEDGER_PATH), 'utf8').then(JSON.parse),
  readCardInputs(root),
]);

/** Reads the intrinsic size out of a PNG header, or fails loudly. */
function readPngSize(image, path) {
  if (
    image.length < 24 ||
    image.readUInt32BE(0) !== 0x89504e47 ||
    image.toString('ascii', 12, 16) !== 'IHDR'
  ) {
    fail(`public${path} is not a valid PNG with an IHDR header`);
    return undefined;
  }

  return { width: image.readUInt32BE(16), height: image.readUInt32BE(20) };
}

async function checkCard(path, expectedDigest, label) {
  let image;
  try {
    image = await readFile(publicFile(root, path));
  } catch {
    fail(`public${path} is missing (${label}). ${REGENERATE}`);
    return;
  }

  const size = readPngSize(image, path);
  if (size && !same(size, EXPECTED_SIZE)) {
    fail(
      `public${path} must be ${EXPECTED_SIZE.width}x${EXPECTED_SIZE.height}; found ${size.width}x${size.height}.`,
    );
  }
  if (imageDigest(image) !== expectedDigest) {
    fail(`public${path} does not match public${LEDGER_PATH}. ${REGENERATE}`);
  }
}

if (!same(ledger.size, EXPECTED_SIZE)) {
  fail(
    `public${LEDGER_PATH} declares ${ledger.size?.width}x${ledger.size?.height}; ` +
      `expected ${EXPECTED_SIZE.width}x${EXPECTED_SIZE.height}.`,
  );
}

if (!same(ledger.profile, inputs.profileSnapshot)) {
  fail(`The share-card profile facts are stale. ${REGENERATE}`);
}

if (!same(ledger.colors, inputs.colors)) {
  fail(`The card colours no longer match the design tokens. ${REGENERATE}`);
}

if (!same(ledger.fonts, inputs.fonts)) {
  fail(`The checksummed share-card fonts are stale. ${REGENERATE}`);
}

if (!same(ledger.renderer, inputs.renderer)) {
  fail(`The locked share-card renderer changed. ${REGENERATE}`);
}

if (ledger.generatorDigest !== inputs.generatorDigest) {
  fail(
    `The share-card generator changed without regenerated cards. ${REGENERATE}`,
  );
}

const ledgerPosts = Array.isArray(ledger.posts) ? ledger.posts : [];
const expectedPosts = inputs.posts.map((post) => post.slug).join(', ');
const actualPosts = ledgerPosts.map((post) => post?.slug).join(', ');

if (expectedPosts !== actualPosts) {
  fail(
    `public${LEDGER_PATH} lists cards for [${actualPosts}]; published posts are ` +
      `[${expectedPosts}]. ${REGENERATE}`,
  );
}

await checkCard(HOME_CARD_PATH, ledger.imageDigest, 'the site card');

for (const [index, post] of inputs.posts.entries()) {
  const recorded = ledgerPosts[index];
  if (recorded?.slug !== post.slug) continue;

  const { imageDigest: recordedDigest, ...snapshot } = recorded;
  if (!same(snapshot, post)) {
    fail(`The card for ${post.slug} no longer matches the post. ${REGENERATE}`);
  }

  await checkCard(post.path, recordedDigest, `the card for ${post.slug}`);
}

// Anything else in the card directory is an artifact of a post that no longer
// publishes — a draft, a rename, or a deletion. `public/` ships verbatim, so a
// leftover file is a live URL carrying an unpublished title.
const expectedFiles = new Set(inputs.posts.map((post) => `${post.slug}.png`));
let cardFiles = [];
try {
  cardFiles = await readdir(publicFile(root, POST_CARD_DIRECTORY));
} catch {
  if (inputs.posts.length > 0) {
    fail(`public${POST_CARD_DIRECTORY}/ is missing. ${REGENERATE}`);
  }
}

for (const file of cardFiles) {
  if (!expectedFiles.has(file)) {
    fail(
      `public${POST_CARD_DIRECTORY}/${file} belongs to no published post. ${REGENERATE}`,
    );
  }
}

if (failures.length > 0) {
  console.error(`\nog:check: ${failures.length} problem(s)\n`);
  for (const message of failures) {
    console.error(`  ${message}`);
  }
  process.exit(1);
}

console.log(
  `og:check: ${1 + inputs.posts.length} cards at ${EXPECTED_SIZE.width}x${EXPECTED_SIZE.height}; ` +
    'images, checksummed fonts, locked renderer, profile facts, colour tokens, post readouts, and generator current',
);
